[package]
name = "arcade-libretro"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = ["audio"]
audio = ["dep:cpal"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("cargo-clippy"))'] }

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
libloading.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
once_cell.workspace = true
glow.workspace = true
ash.workspace = true
cpal = { workspace = true, optional = true }
zip.workspace = true
arcade-domain = { path = "../arcade-domain" }
serde_json.workspace = true
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc = { workspace = true }

[build-dependencies]
cc = "1.1"
naga = { version = "24", features = ["wgsl-in", "spv-out"] }
