[package]
name = "arcade-libretro"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = []
audio = ["dep:cpal"]

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
libloading.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
once_cell.workspace = true
glow.workspace = true
ash.workspace = true
cpal = { workspace = true, optional = true }
zip.workspace = true
arcade-domain = { path = "../arcade-domain" }
tempfile.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.59", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
cc = "1.1"
naga = { version = "24", features = ["wgsl-in", "spv-out"] }
